// strings.js — Alle zichtbare speltekst van Typcoon. Twee kaarten (nl + en, hier
// in één bestand) achter dezelfde sleutels, zodat gt() taal-bewust is zonder dat
// elke call site een taal hoeft mee te geven (assignment 012, §3.7). setLocale()
// zet de actieve taal (uit profile.uiTaal); gt('sleutel', { vars }) leest daaruit.
// De en-kaart dekt nu elke sleutel uit de nl-kaart (assignment 013, volle
// sleutel-pariteit — zie test/locale.test.js voor de pariteits-check in beide
// richtingen). gt() valt nooit terug op nl: een ontbrekende sleutel toont de
// kale sleutel, zodat een gat in de en-kaart meteen zichtbaar is in de tests.

const STRINGS = {
  'brand.name': 'Typcoon',
  'brand.tagline': 'Typ munten. Bouw je fabriek. Word tycoon.',

  'home.start': 'Start je fabriek',
  'home.continue': '▶ Verder bouwen',
  'home.namePlaceholder': 'Jouw naam',
  'home.coins': 'munten',
  'home.stars': 'sterren',
  'home.reset': 'Opnieuw beginnen',
  'home.resetConfirm': 'Weet je het zeker? Je hele fabriek én je sterren zijn dan weg.',
  'home.how1': '⌨️ Typ woorden en verdien munten — hoe netter, hoe meer.',
  'home.how2': '🏭 Koop machines die munten maken zolang jij typt.',
  'home.how3': '⭐ Verkoop je fabriek voor een ster: alles gaat daarna sneller!',
  'home.parents': 'Voor ouders',
  'home.theme': 'Thema’s',
  'home.invite': 'Nodig een vriend uit',
  'home.share': 'Deel je fabriek',
  'home.records': 'Jouw records',
  'home.handsCheck': 'Handen-check',
  'home.emailProgress': 'Voortgang per e-mail',
  'home.emailLinked': 'E-mail gekoppeld',
  'home.otherDevice': 'Al eerder gespeeld? Log in op deze computer',

  'acc.title': 'Voortgang naar de ouder 📧',
  'acc.sub': 'Bewaar de voortgang veilig (verder op elke computer) en krijg een korte wekelijkse voortgangsmail. Voor de ouder — kinderen spelen gewoon zonder account.',
  'acc.emailLabel': 'E-mail van de ouder',
  'acc.userLabel': 'Gebruikersnaam van het kind',
  'acc.userHint': '3–20 tekens: letters, cijfers of _. Hiermee log je later op een andere computer in.',
  'acc.optWeekly': 'Stuur mij een wekelijks voortgangsrapport',
  'acc.optReminders': 'Herinner mij als een reeks dreigt te breken',
  'acc.consent': 'Ik ben de ouder/verzorger en geef toestemming voor deze e-mails.',
  'acc.submit': 'Koppelen & bewaren',
  'acc.busy': 'Even bezig…',
  'acc.trust': 'Alleen jouw e-mail · geen advertenties · elk moment uit te zetten via de link in de mail.',
  'acc.errTaken': 'Die gebruikersnaam is al bezet — kies een andere.',
  'acc.errOffline': 'De koppeling kan nu niet worden gemaakt (server nog niet actief). Het spel werkt gewoon door; probeer het later opnieuw.',
  'acc.errGeneric': 'Er ging iets mis. Probeer het zo nog eens.',
  'acc.doneTitle': 'Gekoppeld! 🎉',
  'acc.doneBody': 'We hebben een bevestiging naar {email} gestuurd. De voortgang wordt nu automatisch bewaard.',
  'acc.doneGo': 'Verder spelen',
  'acc.unlinkConfirm': 'De koppeling met dit apparaat losmaken? Je voortgang blijft lokaal bewaard.',

  'login.title': 'Verder op deze computer 💻',
  'login.sub': 'Vul de gebruikersnaam in. We sturen een inlogcode naar het e-mailadres van de ouder.',
  'login.sendCode': 'Stuur mij een code',
  'login.codeSent': 'We hebben een code gestuurd naar {email}. Kijk in de mailbox van de ouder.',
  'login.codeLabel': '6-cijferige code',
  'login.verify': 'Inloggen',
  'login.errNotFound': 'Die gebruikersnaam kennen we niet. Klopt de spelling?',
  'login.errCode': 'Die code klopt niet (of is verlopen). Vraag eventueel een nieuwe aan.',
  'login.errBusy': 'Even te veel pogingen — wacht een paar minuten en probeer opnieuw.',

  'records.title': '🏆 Jouw records',
  'records.firstWeek': 'Deze week telt! Kom elke dag terug en versla volgende week jezelf.',
  'records.ahead': 'Je bent {n} munten vóór op vorige week! 🚀',
  'records.behind': 'Nog {n} munten om vorige week te verslaan — je kunt het!',
  'records.thisWeek': 'Deze week',
  'records.allTime': 'Records aller tijden',
  'records.weekCoins': 'Munten deze week',
  'records.weekExercises': 'Opdrachten deze week',
  'records.weekCombo': 'Beste combo deze week',
  'records.lastWeek': 'vorige week: {n}',
  'records.bestWeek': 'Beste week ooit',
  'records.bestCombo': 'Hoogste combo',
  'records.longestStreak': 'Langste streak',
  'records.letters': 'Letters geleerd',

  'friends.title': '🎁 Nodig een vriend uit',
  'friends.sub': 'Je vriend krijgt {n} munten cadeau — en als hij goed op weg is, krijg jij er ook!',
  'friends.yourLink': 'Jouw uitnodig-link',
  'friends.copy': 'Kopieer',
  'friends.copied': 'Gekopieerd!',
  'friends.share': 'Deel met een vriend',
  'friends.shareText': 'Kom samen met mij typen én een muntenfabriek bouwen in Typcoon!',
  'friends.rewarded': 'Beloonde vrienden: {n}/{max}',
  'friends.haveToken': 'Heb je een bedankcode van een vriend? Plak ’m hier:',
  'friends.redeem': 'Inwisselen',
  'friends.claimed': 'Gelukt! +{n} munten van je vriend. 🎉',
  'friends.bad': 'Die code klopt niet (of is al gebruikt).',
  'friends.thanksTitle': 'Je vriend krijgt ook een bonus! 🎁',
  'friends.thanksBody': 'Goed bezig! Geef deze bedankcode aan de vriend die jou uitnodigde — dan krijgt hij ook munten:',
  'home.trust': 'Gratis te proberen · geen advertenties · geen in-app aankopen voor je kind',

  'premium.unlockShort': 'Ontgrendel',
  'premium.inFull': 'In de volledige fabriek',
  'premium.chapterTitle': 'Hoofdstuk 1 voltooid! 🎉',
  'premium.chapterBody': 'Wauw — je kent je eerste letters én hebt een echte fabriek gebouwd! In de volledige fabriek leer je álle letters en krijg je alle machines, sterren en thema’s.',
  'premium.chapterCta': 'Bekijk de volledige fabriek',

  'theme.title': 'Kies je thema',
  'theme.sub': 'Het standaard-thema is gratis en compleet. De rest hoort bij de volledige fabriek.',
  'theme.muntpers': 'De Muntpers',
  'theme.muntpers.desc': 'Het standaard-thema: blauwdruk-fabriek met glimmend messing.',
  'theme.nachtploeg': 'Nachtploeg',
  'theme.nachtploeg.desc': 'Je fabriek na sluitingstijd — paars donker met neon-buizen.',
  'theme.snoepfabriek': 'Snoepfabriek',
  'theme.snoepfabriek.desc': 'Een zoete snoepfabriek: bessen-paars met heet-roze hefbomen.',
  'theme.diepzee': 'Diepzee',
  'theme.diepzee.desc': 'Je fabriek op de zeebodem: diep teal met koraal-oranje knoppen.',
  'theme.lockedHint': 'Ontgrendel de volledige fabriek om te wisselen.',

  'unlock.gateTitle': 'Even een volwassene erbij',
  'unlock.gateBody': 'Vraag papa of mama om deze som op te lossen.',
  'unlock.gateGo': 'Volgende',
  'unlock.later': 'Nog even niet',
  'unlock.buyTitle': 'De volledige fabriek',
  'unlock.perkLetters': 'Het hele alfabet leren (alle 26 letters, hoofdletters, leestekens)',
  'unlock.perkMachines': 'Alle 5 machines + onbeperkt sterren verdienen',
  'unlock.perkPrestige': 'Alle thema’s — geef je fabriek een compleet nieuwe look',
  'unlock.perkDashboard': 'Ouder-dashboard: zie de voortgang en nauwkeurigheid',
  'unlock.perkFamily': 'Eén keer betalen — voor het hele gezin, voor altijd',
  'unlock.today': 'alleen vandaag',
  'unlock.trust': 'Eenmalig · geen abonnement · geen advertenties · geen aankopen voor je kind',
  'unlock.buy': 'Ontgrendel voor €{price}',
  'unlock.doneTitle': 'De fabriek is van jullie! 🎉',
  'unlock.doneBody': 'Alles is ontgrendeld. Veel plezier en succes met blind leren typen!',
  'unlock.doneGo': 'Verder spelen',

  'school.linkLabel': 'Schoollicentie-code invoeren',
  'school.title': 'Schoollicentie-code 🏫',
  'school.sub': 'Heeft jouw school een licentie? Voer de code in om de volledige fabriek te ontgrendelen op dit apparaat.',
  'school.label': 'Licentiecode',
  'school.submit': 'Ontgrendel de fabriek',
  'school.errInvalid': 'Die code klopt niet. Controleer of je ’m goed hebt overgetypt.',
  'school.errExpired': 'Deze licentiecode is verlopen. Vraag je school om een nieuwe.',
  'school.errBusy': 'Even te veel pogingen — wacht een paar minuten en probeer opnieuw.',
  'school.errOffline': 'De licentie kan nu niet worden gecontroleerd (server nog niet actief). Probeer het later opnieuw.',
  'school.doneTitle': 'De fabriek is ontgrendeld! 🎉',
  'school.doneBody': 'Dit apparaat heeft nu de volledige fabriek — net als bij de familie-unlock.',
  'school.doneGo': 'Verder spelen',

  'dash.title': '📊 Voor ouders',
  'dash.sub': 'De voortgang van {naam}',
  'dash.letters': 'Letters geleerd',
  'dash.accuracy': 'Nauwkeurigheid',
  'dash.exercises': 'Opdrachten gedaan',
  'dash.combo': 'Beste combo',
  'dash.coins': 'Munten verdiend',
  'dash.stars': 'Sterren',
  'dash.note': 'Typcoon oefent nauwkeurigheid vóór snelheid: netjes typen levert de meeste munten op. Zo leert je kind spelenderwijs blind typen.',
  'dash.unlock': '🔓 Ontgrendel de volledige fabriek',
  'dash.back': '← Terug',
  'dash.examsTitle': '🏅 Behaalde diploma\'s',
  'dash.examEarned': '{name} behaald — {pct}% nauwkeurigheid',
  'dash.examEarnedNoAcc': '{name} behaald',
  'dash.examsNone': 'Nog geen toets behaald — die verschijnt hier zodra er één gehaald is.',

  'share.title': '📸 Deel je fabriek',
  'share.sub': 'Een plaatje van de fabriek — voor de familie-app of om aan opa en oma te laten zien.',
  'share.includeName': 'Naam van {naam} op de kaart zetten',
  'share.privacyNote': 'Dit plaatje wordt alleen op dit apparaat gemaakt — er gaat niets naar een server. Jij bepaalt hierboven of de naam erop staat.',
  'share.download': '⬇️ Download de kaart',
  'share.saved': 'Opgeslagen! ✅',
  'share.cardOwner': 'de fabriek van {naam}',
  'share.cardGeneric': 'mijn fabriek',
  'share.noMachines': 'Nog geen machines — kom terug als de fabriek groeit!',
  'share.cardFooter': 'Getypt met Typcoon 🎮 · typcoon.com',

  'play.back': '← Menu',
  'play.soundOff': 'Geluid uit',
  'play.soundOn': 'Geluid aan',

  'daily.streakTip': 'Je bent {n} dagen op rij bezig! Kom morgen terug om je streak te laten groeien.',
  'daily.boostChip': '🔥 Opwarm-boost ×{mult} — nog {n} opdrachten',
  'daily.welcomeTitle': 'Welkom terug! Dag {n} 🔥',
  'daily.welcomeBoost': 'Je eerste {n} opdrachten vandaag leveren ×{mult} munten op — warm die vingers op!',
  'daily.welcomeBonus': '{streak}-dagen streak-bonus!',
  'daily.welcomeGo': 'Aan de slag!',
  'play.coins': 'Munten',
  'play.perSec': 'Munten per seconde (zolang je typt)',
  'play.stars': 'Sterren: alles ×{mult}',
  'play.factory': 'Machines',
  'play.upgrades': 'Upgrades',
  'play.tabFloor': '🏭 Fabriek',
  'play.tabShop': '🛒 Winkel',
  'play.accuracyLever': '{pct}% netjes — netter typen = meer munten!',
  'play.combo': 'combo',
  'play.flashNeat': 'netjes',
  'play.flashGold': 'goud',
  'play.flashWarmup': 'opwarm',
  'play.typeHint': 'Typ de letters om je eerste munten te maken',
  'play.golden': '✨ GOUDEN OPDRACHT — 3× munten! ✨',
  'play.unlockAt': 'Leer {n} letters om te ontgrendelen',
  'play.unlockIn': 'Nog {n} letters leren om te ontgrendelen',
  'play.unlockIn1': 'Nog 1 letter leren om te ontgrendelen',
  'play.nextMilestone': 'Lv {n} → tempo ×2',
  'play.milestoneReached': 'MIJLPAAL! {name} draait nu 2× zo snel!',
  'play.newMachineTitle': 'Nieuwe machine ontdekt!',
  'play.newMachineBody': 'Je leerde een nieuwe letter én ontgrendelde de {name}. Koop ’m voor meer munten!',
  'play.newLetterTitle': 'Nieuwe letter!',
  'play.newLetterBody': 'Je kunt nu ook {keys} typen. Meer letters = meer machines!',
  'play.nice': 'Gaaf!',
  'play.checkHands': '🏠 Even checken: vingers weer op de thuisrij?',

  'reminders.home': 'Vingers terug op de thuisrij! 🏠',
  'reminders.peek': 'Niet spieken — voel de bultjes op F en J 👀',

  'onb.introTitle': 'Jouw vingers zijn de werkers 🧤',
  'onb.introBody': 'Elke vinger heeft een eigen kleur én een eigen plekje op het toetsenbord. Zie je dezelfde kleuren op de toetsen? Zo weet elke vinger precies waar hij hoort.',
  'onb.introGo': 'Laat maar zien! →',
  'onb.homeTitle': 'Vind je huis 🏠',
  'onb.homeBody': 'Leg je linkerhand op A S D F en je rechterhand op J K L ;. Voel je de kleine bultjes op F en J? Daar liggen je twee wijsvingers — zo vind je de thuisrij zonder te kijken.',
  'onb.homeGo': 'Ik voel de bultjes!',
  'onb.drillTitle': 'Nu jij! 💪',
  'onb.drillBody': 'Typ deze rij na. Laat je vingers op hun kleur-plek staan en breng ze na elke toets weer terug naar huis. Rustig aan — het gaat om netjes, niet om snel.',
  'onb.drillHint': 'Tip: kijk naar het scherm, niet naar je handen. Je kunt het! 🌟',
  'onb.powerTitle': 'Dat is je superkracht! ⚡',
  'onb.powerBody': 'Zie je? Je hoeft niet naar je handen te kijken. Blind typen is je geheime superkracht: je wordt razendsnel, en zo blijft jouw fabriek straks vanzelf munten maken. Klaar om te bouwen?',
  'onb.powerGo': 'Ik ben er klaar voor! 🚀',
  'onb.refreshTitle': 'Even opfrissen ✋',
  'onb.refreshBody': 'Handen op de thuisrij — wijsvingers op de bultjes van F en J. Typ dit rijtje om je vingers wakker te maken.',
  'onb.skip': 'Overslaan',
  'play.idleFloor': 'De machines wachten op jou — typ om ze aan te zetten!',
  'play.floorEmpty': 'Nog geen machines. Verdien munten met typen en koop je eerste!',
  'play.achievement': 'Prestatie behaald!',

  'rebirth.button': '⭐ Verkoop je fabriek',
  'rebirth.locked': 'Verdien {n} munten om je fabriek te kunnen verkopen',
  'rebirth.title': 'Fabriek verkopen?',
  'rebirth.body': 'Je munten, machines en upgrades gaan weg — maar je krijgt een STER: alles wat je hierna verdient is voorgoed ×{mult}. Je geleerde letters houd je natuurlijk!',
  'rebirth.confirm': 'Verkopen — geef mij die ster! ⭐',
  'rebirth.cancel': 'Nog even doorbouwen',
  'rebirth.doneTitle': 'Ster verdiend! ⭐',
  'rebirth.doneBody': 'Je fabriek is verkocht. Alles wat je nu verdient is ×{mult}. Bouw ’m sneller terug dan ooit!',

  'building.typewriter': 'Typemachine',
  'building.typewriter.desc': 'Tikt langzaam munten uit',
  'building.printer': 'Drukpers',
  'building.printer.desc': 'Drukt munten in stapels',
  'building.robotarm': 'Robotarm',
  'building.robotarm.desc': 'Werkt onvermoeibaar door',
  'building.assembly': 'Lopende band',
  'building.assembly.desc': 'Een hele hal vol munten',
  'building.megafab': 'Mega-fabriek',
  'building.megafab.desc': 'Munten met bakken tegelijk',

  'upgrade.oil': 'Smeerolie',
  'upgrade.turbo': 'Turbomotor',
  'upgrade.precision': 'Precisiegereedschap',
  'upgrade.golden': 'Gouden toetsen',
  'upgrade.prod': 'Alle machines ×{x} sneller',
  'upgrade.payout': 'Elke opdracht ×{x} munten',

  'ach.eerste-munt': 'Eerste munt',
  'ach.eerste-machine': 'Eerste machine',
  'ach.duizend': '1.000 munten verdiend',
  'ach.tienduizend': '10.000 munten verdiend',
  'ach.honderdduizend': '100.000 munten verdiend',
  'ach.combo-25': 'Combo van 25',
  'ach.combo-50': 'Combo van 50',
  'ach.eerste-goud': 'Eerste gouden opdracht',
  'ach.goud-10': '10 gouden opdrachten',
  'ach.vijf-letters': '5 letters geleerd',
  'ach.tien-letters': '10 letters geleerd',
  'ach.alle-letters': 'Alle letters geleerd!',
  'ach.eerste-rebirth': 'Eerste ster',
  'ach.drie-rebirths': 'Drie sterren',
  'ach.honderd-oefeningen': '100 opdrachten gedaan',

  'desktop.title': 'Pak een toetsenbord erbij!',
  'desktop.body': 'Typcoon speel je met een echt toetsenbord — op een laptop of computer. Tot zo!',

  // Toetsen/typdiploma (assignment 049): optioneel, nooit gating — puur erkenning.
  'exam.pillLabel': 'Toets beschikbaar',
  'exam.banner': 'TOETS: {name}',
  'exam.offerTitle': 'Klaar voor een toets? 🏅',
  'exam.offerBody': 'Je kent deze letters goed! Wil je de {name} proberen? Gewoon voor de eer — lukt het niet, dan speel je gewoon verder.',
  'exam.offerStart': 'Start de toets!',
  'exam.offerDecline': 'Nog even niet',
  'exam.passTitle': 'Toets gehaald! 🎉',
  'exam.passBody': 'Knap gedaan! Je haalde de {name} met {pct}% nauwkeurig.',
  'exam.failTitle': 'Nog niet helemaal — geen zorgen!',
  'exam.failBody': 'Je zat op {pct}% nauwkeurig. Oefen nog even door, dan lukt de toets zo!',
  'exam.exam-1': 'Thuisrij-toets',
  'exam.exam-2': 'Bovenrij-toets',
  'exam.exam-3': 'Alfabet-toets',
  'exam.exam-4': 'Hoofdletters-toets',
  'exam.exam-final': 'Typdiploma',

  // diploma-certificaat (assignment 050) — verschijnt in het examPass-vier-moment
  'cert.kicker': 'TYPCOON CERTIFICAAT',
  'cert.for': 'Voor {naam}',
  'cert.accuracyLabel': 'nauwkeurigheid',
  'cert.print': '🖨️ Print of bewaar',

  // kleine taal-neutrale bouwstenen die in JS-logica (niet in strings.js zelf)
  // een taal-specifiek woordje nodig hadden — hoorden hier al thuis, waren
  // per ongeluk hardgecodeerd in GameScreen.jsx (zie assignment 012).
  'common.and': 'en',
  'play.buyLabel': '{name} kopen',

  // vingernamen voor de handen-uitleg + het toetsenbord-hintje (§3.6): dezelfde
  // sleutels als de `finger`-waarden in de layouts, zodat de hint vertaalbaar is.
  'fingers.left-pinky': 'linker pink',
  'fingers.left-ring': 'linker ringvinger',
  'fingers.left-middle': 'linker middelvinger',
  'fingers.left-index': 'linker wijsvinger',
  'fingers.right-index': 'rechter wijsvinger',
  'fingers.right-middle': 'rechter middelvinger',
  'fingers.right-ring': 'rechter ringvinger',
  'fingers.right-pinky': 'rechter pink',
  'fingers.thumb': 'duim',
  'fingers.use': 'Gebruik je {finger}.',
  'fingers.bothHome': 'Beide handen op de thuisrij: linkerhand A S D F, rechterhand J K L ;, duimen op de spatie.',
};

// en — Engelse speltekst (assignment 012 legde de basis, §3.7; assignment 013
// levert de volle sleutel-pariteit met nl — zie test/locale.test.js voor de
// pariteits-check in beide richtingen). Volgorde spiegelt de nl-kaart hierboven
// zodat de twee kaarten side-by-side te vergelijken zijn.
const STRINGS_EN = {
  'brand.name': 'Typcoon',
  'brand.tagline': 'Type coins. Build your factory. Become a tycoon.',

  'home.start': 'Start your factory',
  'home.continue': '▶ Keep building',
  'home.namePlaceholder': 'Your name',
  'home.coins': 'coins',
  'home.stars': 'stars',
  'home.reset': 'Start over',
  'home.resetConfirm': 'Are you sure? Your whole factory and your stars will be gone.',
  'home.how1': '⌨️ Type words and earn coins — the neater you type, the more you earn.',
  'home.how2': '🏭 Buy machines that make coins as long as you keep typing.',
  'home.how3': '⭐ Sell your factory for a star: everything after that goes faster!',
  'home.parents': 'For parents',
  'home.theme': 'Themes',
  'home.invite': 'Invite a friend',
  'home.share': 'Share your factory',
  'home.records': 'Your records',
  'home.handsCheck': 'Hand check',
  'home.emailProgress': 'Progress by email',
  'home.emailLinked': 'Email linked',
  'home.otherDevice': 'Played before? Log in on this computer',

  'acc.title': 'Progress to the parent 📧',
  'acc.sub': "Save your progress safely (keep going on any computer) and get a short weekly progress email. For the parent — kids just play, no account needed.",
  'acc.emailLabel': "Parent's email",
  'acc.userLabel': "Child's username",
  'acc.userHint': '3–20 characters: letters, numbers or _. You’ll use this to log in on another computer later.',
  'acc.optWeekly': 'Send me a weekly progress report',
  'acc.optReminders': 'Remind me if a streak is about to break',
  'acc.consent': 'I am the parent/guardian and give consent for these emails.',
  'acc.submit': 'Link & save',
  'acc.busy': 'Just a moment…',
  'acc.trust': 'Only your email · no ads · unsubscribe any time via the link in the email.',
  'acc.errTaken': 'That username is already taken — pick another one.',
  'acc.errOffline': "The link can't be made right now (server not active yet). The game keeps working fine; try again later.",
  'acc.errGeneric': 'Something went wrong. Please try again.',
  'acc.doneTitle': 'Linked! 🎉',
  'acc.doneBody': 'We sent a confirmation to {email}. Your progress is now saved automatically.',
  'acc.doneGo': 'Keep playing',
  'acc.unlinkConfirm': 'Unlink from this device? Your progress stays saved locally.',

  'login.title': 'Continue on this computer 💻',
  'login.sub': "Enter the username. We'll send a login code to the parent's email address.",
  'login.sendCode': 'Send me a code',
  'login.codeSent': "We sent a code to {email}. Check the parent's inbox.",
  'login.codeLabel': '6-digit code',
  'login.verify': 'Log in',
  'login.errNotFound': "We don't recognise that username. Is it spelled right?",
  'login.errCode': "That code isn't right (or it's expired). You can request a new one.",
  'login.errBusy': 'Too many attempts for now — wait a few minutes and try again.',

  'records.title': '🏆 Your records',
  'records.firstWeek': 'This week counts! Come back every day and beat yourself next week.',
  'records.ahead': "You're {n} coins ahead of last week! 🚀",
  'records.behind': "{n} more coins to beat last week — you can do it!",
  'records.thisWeek': 'This week',
  'records.allTime': 'All-time records',
  'records.weekCoins': 'Coins this week',
  'records.weekExercises': 'Tasks this week',
  'records.weekCombo': 'Best combo this week',
  'records.lastWeek': 'last week: {n}',
  'records.bestWeek': 'Best week ever',
  'records.bestCombo': 'Highest combo',
  'records.longestStreak': 'Longest streak',
  'records.letters': 'Letters learned',

  'friends.title': '🎁 Invite a friend',
  'friends.sub': "Your friend gets {n} coins as a gift — and once they're off to a good start, you get some too!",
  'friends.yourLink': 'Your invite link',
  'friends.copy': 'Copy',
  'friends.copied': 'Copied!',
  'friends.share': 'Share with a friend',
  'friends.shareText': 'Come type with me and build a coin factory together in Typcoon!',
  'friends.rewarded': 'Rewarded friends: {n}/{max}',
  'friends.haveToken': 'Got a thank-you code from a friend? Paste it here:',
  'friends.redeem': 'Redeem',
  'friends.claimed': 'Success! +{n} coins from your friend. 🎉',
  'friends.bad': "That code isn't right (or has already been used).",
  'friends.thanksTitle': 'Your friend gets a bonus too! 🎁',
  'friends.thanksBody': 'Nice work! Give this thank-you code to the friend who invited you — then they get coins too:',
  'home.trust': 'Free to try · no ads · no in-app purchases for your child',

  'premium.unlockShort': 'Unlock',
  'premium.inFull': 'In the full factory',
  'premium.chapterTitle': 'Chapter 1 complete! 🎉',
  'premium.chapterBody': 'Wow — you know your first letters and built a real factory! In the full factory you learn ALL the letters and get every machine, star and theme.',
  'premium.chapterCta': 'See the full factory',

  'theme.title': 'Choose your theme',
  'theme.sub': 'The default theme is free and complete. The rest comes with the full factory.',
  'theme.muntpers': 'The Coin Press',
  'theme.muntpers.desc': 'The default look: blueprint factory with polished brass.',
  'theme.nachtploeg': 'Night Shift',
  'theme.nachtploeg.desc': 'Your factory after hours — deep purple lit by neon tubes.',
  'theme.snoepfabriek': 'Sugar Rush',
  'theme.snoepfabriek.desc': 'A sweet candy plant: berry-purple with hot-pink levers.',
  'theme.diepzee': 'Deep Dive',
  'theme.diepzee.desc': 'Your factory on the seabed: deep teal with coral-orange buttons.',
  'theme.lockedHint': 'Unlock the full factory to switch.',

  'unlock.gateTitle': 'Grab a grown-up',
  'unlock.gateBody': 'Ask mom or dad to solve this sum.',
  'unlock.gateGo': 'Next',
  'unlock.later': 'Not right now',
  'unlock.buyTitle': 'The full factory',
  'unlock.perkLetters': 'Learn the whole alphabet (all 26 letters, capitals, punctuation)',
  'unlock.perkMachines': 'All 5 machines + unlimited stars',
  'unlock.perkPrestige': 'Every theme — give your whole factory a fresh look',
  'unlock.perkDashboard': 'Parent dashboard: see progress and accuracy',
  'unlock.perkFamily': 'Pay once — for the whole family, forever',
  'unlock.today': 'today only',
  'unlock.trust': 'One-time · no subscription · no ads · no purchases for your child',
  'unlock.buy': 'Unlock for €{price}',
  'unlock.doneTitle': 'The factory is yours! 🎉',
  'unlock.doneBody': 'Everything is unlocked. Have fun learning to touch type!',
  'unlock.doneGo': 'Keep playing',

  'school.linkLabel': 'Enter school licence code',
  'school.title': 'School licence code 🏫',
  'school.sub': 'Does your school have a licence? Enter the code to unlock the full factory on this device.',
  'school.label': 'Licence code',
  'school.submit': 'Unlock the factory',
  'school.errInvalid': "That code isn't right. Check that you typed it correctly.",
  'school.errExpired': 'This licence code has expired. Ask your school for a new one.',
  'school.errBusy': 'Too many attempts for now — wait a few minutes and try again.',
  'school.errOffline': "The licence can't be checked right now (server not active yet). Try again later.",
  'school.doneTitle': 'The factory is unlocked! 🎉',
  'school.doneBody': 'This device now has the full factory — just like the family unlock.',
  'school.doneGo': 'Keep playing',

  'dash.title': '📊 For parents',
  'dash.sub': "{naam}'s progress",
  'dash.letters': 'Letters learned',
  'dash.accuracy': 'Accuracy',
  'dash.exercises': 'Tasks completed',
  'dash.combo': 'Best combo',
  'dash.coins': 'Coins earned',
  'dash.stars': 'Stars',
  'dash.note': "Typcoon trains accuracy before speed: typing neatly earns the most coins. That's how your child learns to touch type, one game at a time.",
  'dash.unlock': '🔓 Unlock the full factory',
  'dash.back': '← Back',
  'dash.examsTitle': '🏅 Diplomas earned',
  'dash.examEarned': '{name} passed — {pct}% accuracy',
  'dash.examEarnedNoAcc': '{name} passed',
  'dash.examsNone': 'No exam passed yet — it will show up here as soon as one is earned.',

  'share.title': '📸 Share your factory',
  'share.sub': 'A picture of the factory — for the family chat or to show grandma and grandpa.',
  'share.includeName': "Put {naam}'s name on the card",
  'share.privacyNote': "This picture is only made on this device — nothing goes to a server. You decide above whether the name appears on it.",
  'share.download': '⬇️ Download the card',
  'share.saved': 'Saved! ✅',
  'share.cardOwner': "{naam}'s factory",
  'share.cardGeneric': 'my factory',
  'share.noMachines': 'No machines yet — come back once the factory grows!',
  'share.cardFooter': 'Typed with Typcoon 🎮 · typcoon.com',

  'play.back': '← Menu',
  'play.soundOff': 'Sound off',
  'play.soundOn': 'Sound on',
  'play.coins': 'Coins',
  'play.perSec': 'Coins per second (while you type)',
  'play.stars': 'Stars: everything ×{mult}',
  'play.factory': 'Machines',
  'play.upgrades': 'Upgrades',
  'play.tabFloor': '🏭 Factory',
  'play.tabShop': '🛒 Shop',
  'play.accuracyLever': '{pct}% neat — neater typing = more coins!',
  'play.combo': 'combo',
  'play.flashNeat': 'neat',
  'play.flashGold': 'gold',
  'play.flashWarmup': 'warm-up',
  'play.typeHint': 'Type the letters to make your first coins',
  'play.golden': '✨ GOLDEN TASK — 3× coins! ✨',
  'play.unlockAt': 'Learn {n} letters to unlock',
  'play.unlockIn': '{n} more letters to unlock',
  'play.unlockIn1': '1 more letter to unlock',
  'play.nextMilestone': 'Lv {n} → speed ×2',
  'play.milestoneReached': 'MILESTONE! {name} now runs 2× as fast!',
  'play.newMachineTitle': 'New machine discovered!',
  'play.newMachineBody': 'You learned a new letter and unlocked the {name}. Buy it for more coins!',
  'play.newLetterTitle': 'New letter!',
  'play.newLetterBody': 'You can now also type {keys}. More letters = more machines!',
  'play.nice': 'Nice!',
  'play.checkHands': '🏠 Quick check: fingers back on the home row?',
  'play.idleFloor': 'The machines are waiting for you — type to switch them on!',
  'play.floorEmpty': 'No machines yet. Earn coins by typing and buy your first one!',
  'play.achievement': 'Achievement unlocked!',
  'play.buyLabel': 'Buy {name}',

  'reminders.home': 'Fingers back on the home row! 🏠',
  'reminders.peek': "Don't peek — feel the bumps on F and J 👀",

  'onb.introTitle': 'Your fingers are the workers 🧤',
  'onb.introBody': 'Every finger has its own colour and its own spot on the keyboard. See the same colours on the keys? That is how each finger knows exactly where it belongs.',
  'onb.introGo': 'Show me! →',
  'onb.homeTitle': 'Find your home 🏠',
  'onb.homeBody': 'Rest your left hand on A S D F and your right hand on J K L ;. Feel the little bumps on F and J? Those are your two index fingers — that is how you find the home row without looking.',
  'onb.homeGo': 'I feel the bumps!',
  'onb.drillTitle': 'Your turn! 💪',
  'onb.drillBody': 'Type this row. Keep your fingers on their colour spot and bring them back home after every key. Take it slow — this is about neat, not fast.',
  'onb.drillHint': "Tip: look at the screen, not at your hands. You've got this! 🌟",
  'onb.powerTitle': 'That is your superpower! ⚡',
  'onb.powerBody': "See? You didn't need to look at your hands. Touch typing is your secret superpower: you'll get super fast, and that keeps your factory making coins on its own. Ready to build?",
  'onb.powerGo': "I'm ready! 🚀",
  'onb.refreshTitle': 'Quick refresher ✋',
  'onb.refreshBody': 'Hands on the home row — index fingers on the bumps of F and J. Type this row to wake your fingers up.',
  'onb.skip': 'Skip',

  'daily.streakTip': "You've kept it up for {n} days in a row! Come back tomorrow to grow your streak.",
  'daily.boostChip': '🔥 Warm-up boost ×{mult} — {n} tasks left',
  'daily.welcomeTitle': 'Welcome back! Day {n} 🔥',
  'daily.welcomeBoost': 'Your first {n} tasks today earn ×{mult} coins — warm up those fingers!',
  'daily.welcomeBonus': '{streak}-day streak bonus!',
  'daily.welcomeGo': "Let's go!",

  'rebirth.button': '⭐ Sell your factory',
  'rebirth.locked': 'Earn {n} coins to be able to sell your factory',
  'rebirth.title': 'Sell the factory?',
  'rebirth.body': 'Your coins, machines and upgrades go away — but you get a STAR: everything you earn after this is forever ×{mult}. You keep your learned letters, of course!',
  'rebirth.confirm': 'Sell — give me that star! ⭐',
  'rebirth.cancel': 'Keep building a bit longer',
  'rebirth.doneTitle': 'Star earned! ⭐',
  'rebirth.doneBody': "Your factory is sold. Everything you earn now is ×{mult}. Build it back faster than ever!",

  'building.typewriter': 'Typewriter',
  'building.typewriter.desc': 'Taps out coins slowly',
  'building.printer': 'Printing press',
  'building.printer.desc': 'Prints coins in stacks',
  'building.robotarm': 'Robot arm',
  'building.robotarm.desc': 'Works tirelessly on',
  'building.assembly': 'Conveyor belt',
  'building.assembly.desc': 'A whole hall full of coins',
  'building.megafab': 'Mega factory',
  'building.megafab.desc': 'Coins by the bucketload',

  'upgrade.oil': 'Oil can',
  'upgrade.turbo': 'Turbo engine',
  'upgrade.precision': 'Precision tools',
  'upgrade.golden': 'Golden keys',
  'upgrade.prod': 'Every machine ×{x} faster',
  'upgrade.payout': 'Every task ×{x} coins',

  'ach.eerste-munt': 'First coin',
  'ach.eerste-machine': 'First machine',
  'ach.duizend': '1,000 coins earned',
  'ach.tienduizend': '10,000 coins earned',
  'ach.honderdduizend': '100,000 coins earned',
  'ach.combo-25': 'Combo of 25',
  'ach.combo-50': 'Combo of 50',
  'ach.eerste-goud': 'First golden task',
  'ach.goud-10': '10 golden tasks',
  'ach.vijf-letters': '5 letters learned',
  'ach.tien-letters': '10 letters learned',
  'ach.alle-letters': 'All letters learned!',
  'ach.eerste-rebirth': 'First star',
  'ach.drie-rebirths': 'Three stars',
  'ach.honderd-oefeningen': '100 tasks done',

  'desktop.title': 'Grab a keyboard!',
  'desktop.body': 'Typcoon is played with a real keyboard — on a laptop or computer. See you there!',

  // Exams/typing diploma (assignment 049): optional, never gating — recognition only.
  'exam.pillLabel': 'Exam available',
  'exam.banner': 'EXAM: {name}',
  'exam.offerTitle': 'Ready for an exam? 🏅',
  'exam.offerBody': "You know these letters well! Want to try the {name}? Just for the glory — if it doesn't go your way, you just keep playing.",
  'exam.offerStart': 'Start the exam!',
  'exam.offerDecline': 'Not right now',
  'exam.passTitle': 'Exam passed! 🎉',
  'exam.passBody': 'Nice work! You passed the {name} with {pct}% accuracy.',
  'exam.failTitle': "Not quite yet — no worries!",
  'exam.failBody': "You were at {pct}% accuracy. Practise a bit more and you'll ace it!",
  'exam.exam-1': 'Home Row Exam',
  'exam.exam-2': 'Upper Row Exam',
  'exam.exam-3': 'Alphabet Exam',
  'exam.exam-4': 'Capitals Exam',
  'exam.exam-final': 'Typing Diploma',

  'cert.kicker': 'TYPCOON CERTIFICATE',
  'cert.for': 'For {naam}',
  'cert.accuracyLabel': 'accuracy',
  'cert.print': '🖨️ Print or save',

  'common.and': 'and',

  'fingers.left-pinky': 'left pinky',
  'fingers.left-ring': 'left ring finger',
  'fingers.left-middle': 'left middle finger',
  'fingers.left-index': 'left index finger',
  'fingers.right-index': 'right index finger',
  'fingers.right-middle': 'right middle finger',
  'fingers.right-ring': 'right ring finger',
  'fingers.right-pinky': 'right pinky',
  'fingers.thumb': 'thumb',
  'fingers.use': 'Use your {finger}.',
  'fingers.bothHome': 'Both hands on the home row: left hand A S D F, right hand J K L ;, thumbs on the space bar.',
};

const LOCALES = { nl: STRINGS, en: STRINGS_EN };
let activeLocale = 'nl';

// Actieve UI-taal zetten (uit profile.uiTaal). Onbekende locale valt terug op nl.
export function setLocale(locale) {
  activeLocale = LOCALES[locale] ? locale : 'nl';
}

export function getLocale() {
  return activeLocale;
}

// Sleutels van een taalkaart (voor de nl/en pariteitstest — assignment 013).
// Geen productie-call-site mag hierlangs tekst lezen; gt() blijft het enige pad.
export function localeKeys(locale) {
  return Object.keys(LOCALES[locale] || {});
}

export function gt(key, vars) {
  const table = LOCALES[activeLocale] || STRINGS;
  // Val NOOIT terug op de NL-tekst — dat zou juist Nederlands laten zien in een
  // en-sessie. Een ontbrekende sleutel toont de kale sleutel (nu alleen bereikbaar
  // via een echte typefout, want en/nl zijn sleutel-voor-sleutel gelijk — assignment 013).
  const raw = table[key];
  if (raw == null) return key;
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (_, k) => (k in vars ? String(vars[k]) : `{${k}}`));
}
