// strings.js — Alle zichtbare speltekst van Typcoon (Nederlands). Eén plek, zodat
// een tweede taal later één extra bestand is. Mini-API: gt('sleutel', { vars }).

const STRINGS = {
  'brand.name': 'Typcoon',
  'brand.tagline': 'Typ munten. Bouw je fabriek. Word tycoon.',

  'home.start': 'Start je fabriek',
  'home.continue': '▶ Verder bouwen',
  'home.namePlaceholder': 'Jouw naam',
  'home.coins': 'munten',
  'home.stars': 'sterren',
  'home.reset': 'Opnieuw beginnen',
  'home.resetConfirm': 'Weet je het zeker? Je hele fabriek én je sterren zijn dan weg.',
  'home.how1': '⌨️ Typ woorden en verdien munten — hoe netter, hoe meer.',
  'home.how2': '🏭 Koop machines die munten maken zolang jij typt.',
  'home.how3': '⭐ Verkoop je fabriek voor een ster: alles gaat daarna sneller!',
  'home.parents': 'Voor ouders',
  'home.invite': 'Nodig een vriend uit',
  'home.records': 'Jouw records',

  'records.title': '🏆 Jouw records',
  'records.firstWeek': 'Deze week telt! Kom elke dag terug en versla volgende week jezelf.',
  'records.ahead': 'Je bent {n} munten vóór op vorige week! 🚀',
  'records.behind': 'Nog {n} munten om vorige week te verslaan — je kunt het!',
  'records.thisWeek': 'Deze week',
  'records.allTime': 'Records aller tijden',
  'records.weekCoins': 'Munten deze week',
  'records.weekExercises': 'Opdrachten deze week',
  'records.weekCombo': 'Beste combo deze week',
  'records.lastWeek': 'vorige week: {n}',
  'records.bestWeek': 'Beste week ooit',
  'records.bestCombo': 'Hoogste combo',
  'records.longestStreak': 'Langste streak',
  'records.letters': 'Letters geleerd',

  'friends.title': '🎁 Nodig een vriend uit',
  'friends.sub': 'Je vriend krijgt {n} munten cadeau — en als hij goed op weg is, krijg jij er ook!',
  'friends.yourLink': 'Jouw uitnodig-link',
  'friends.copy': 'Kopieer',
  'friends.copied': 'Gekopieerd!',
  'friends.share': 'Deel met een vriend',
  'friends.shareText': 'Kom samen met mij typen én een muntenfabriek bouwen in Typcoon!',
  'friends.rewarded': 'Beloonde vrienden: {n}/{max}',
  'friends.haveToken': 'Heb je een bedankcode van een vriend? Plak ’m hier:',
  'friends.redeem': 'Inwisselen',
  'friends.claimed': 'Gelukt! +{n} munten van je vriend. 🎉',
  'friends.bad': 'Die code klopt niet (of is al gebruikt).',
  'friends.thanksTitle': 'Je vriend krijgt ook een bonus! 🎁',
  'friends.thanksBody': 'Goed bezig! Geef deze bedankcode aan de vriend die jou uitnodigde — dan krijgt hij ook munten:',
  'home.trust': 'Gratis te proberen · geen advertenties · geen in-app aankopen voor je kind',

  'premium.unlockShort': 'Ontgrendel',
  'premium.inFull': 'In de volledige fabriek',
  'premium.chapterTitle': 'Hoofdstuk 1 voltooid! 🎉',
  'premium.chapterBody': 'Wauw — je kent je eerste letters én hebt een echte fabriek gebouwd! In de volledige fabriek leer je álle letters en krijg je alle machines, sterren en thema’s.',
  'premium.chapterCta': 'Bekijk de volledige fabriek',

  'unlock.gateTitle': 'Even een volwassene erbij',
  'unlock.gateBody': 'Vraag papa of mama om deze som op te lossen.',
  'unlock.gateGo': 'Volgende',
  'unlock.later': 'Nog even niet',
  'unlock.buyTitle': 'De volledige fabriek',
  'unlock.perkLetters': 'Het hele alfabet leren (alle 26 letters, hoofdletters, leestekens)',
  'unlock.perkMachines': 'Alle 5 machines + onbeperkt sterren verdienen',
  'unlock.perkPrestige': 'Alle thema’s en fabrieks-uitbreidingen',
  'unlock.perkDashboard': 'Ouder-dashboard: zie de voortgang en nauwkeurigheid',
  'unlock.perkFamily': 'Eén keer betalen — voor het hele gezin, voor altijd',
  'unlock.today': 'alleen vandaag',
  'unlock.trust': 'Eenmalig · geen abonnement · geen advertenties · geen aankopen voor je kind',
  'unlock.buy': 'Ontgrendel voor €{price}',
  'unlock.doneTitle': 'De fabriek is van jullie! 🎉',
  'unlock.doneBody': 'Alles is ontgrendeld. Veel plezier en succes met blind leren typen!',
  'unlock.doneGo': 'Verder spelen',

  'dash.title': '📊 Voor ouders',
  'dash.sub': 'De voortgang van {naam}',
  'dash.letters': 'Letters geleerd',
  'dash.accuracy': 'Nauwkeurigheid',
  'dash.exercises': 'Opdrachten gedaan',
  'dash.combo': 'Beste combo',
  'dash.coins': 'Munten verdiend',
  'dash.stars': 'Sterren',
  'dash.note': 'Typcoon oefent nauwkeurigheid vóór snelheid: netjes typen levert de meeste munten op. Zo leert je kind spelenderwijs blind typen.',
  'dash.unlock': '🔓 Ontgrendel de volledige fabriek',
  'dash.back': '← Terug',

  'play.back': '← Menu',
  'play.soundOff': 'Geluid uit',
  'play.soundOn': 'Geluid aan',

  'daily.streakTip': 'Je bent {n} dagen op rij bezig! Kom morgen terug om je streak te laten groeien.',
  'daily.boostChip': '🔥 Opwarm-boost ×{mult} — nog {n} opdrachten',
  'daily.welcomeTitle': 'Welkom terug! Dag {n} 🔥',
  'daily.welcomeBoost': 'Je eerste {n} opdrachten vandaag leveren ×{mult} munten op — warm die vingers op!',
  'daily.welcomeBonus': '{streak}-dagen streak-bonus!',
  'daily.welcomeGo': 'Aan de slag!',
  'play.coins': 'Munten',
  'play.perSec': 'Munten per seconde (zolang je typt)',
  'play.stars': 'Sterren: alles ×{mult}',
  'play.factory': 'Machines',
  'play.upgrades': 'Upgrades',
  'play.tabFloor': '🏭 Fabriek',
  'play.tabShop': '🛒 Winkel',
  'play.accuracyLever': '{pct}% netjes — netter typen = meer munten!',
  'play.combo': 'combo',
  'play.typeHint': 'Typ de letters om je eerste munten te maken',
  'play.golden': '✨ GOUDEN OPDRACHT — 3× munten! ✨',
  'play.unlockAt': 'Leer {n} letters om te ontgrendelen',
  'play.unlockIn': 'Nog {n} letters leren om te ontgrendelen',
  'play.unlockIn1': 'Nog 1 letter leren om te ontgrendelen',
  'play.nextMilestone': 'Lv {n} → tempo ×2',
  'play.milestoneReached': 'MIJLPAAL! {name} draait nu 2× zo snel!',
  'play.newMachineTitle': 'Nieuwe machine ontdekt!',
  'play.newMachineBody': 'Je leerde een nieuwe letter én ontgrendelde de {name}. Koop ’m voor meer munten!',
  'play.newLetterTitle': 'Nieuwe letter!',
  'play.newLetterBody': 'Je kunt nu ook {keys} typen. Meer letters = meer machines!',
  'play.nice': 'Gaaf!',
  'play.idleFloor': 'De machines wachten op jou — typ om ze aan te zetten!',
  'play.floorEmpty': 'Nog geen machines. Verdien munten met typen en koop je eerste!',
  'play.achievement': 'Prestatie behaald!',

  'rebirth.button': '⭐ Verkoop je fabriek',
  'rebirth.locked': 'Verdien {n} munten om je fabriek te kunnen verkopen',
  'rebirth.title': 'Fabriek verkopen?',
  'rebirth.body': 'Je munten, machines en upgrades gaan weg — maar je krijgt een STER: alles wat je hierna verdient is voorgoed ×{mult}. Je geleerde letters houd je natuurlijk!',
  'rebirth.confirm': 'Verkopen — geef mij die ster! ⭐',
  'rebirth.cancel': 'Nog even doorbouwen',
  'rebirth.doneTitle': 'Ster verdiend! ⭐',
  'rebirth.doneBody': 'Je fabriek is verkocht. Alles wat je nu verdient is ×{mult}. Bouw ’m sneller terug dan ooit!',

  'building.typewriter': 'Typemachine',
  'building.typewriter.desc': 'Tikt langzaam munten uit',
  'building.printer': 'Drukpers',
  'building.printer.desc': 'Drukt munten in stapels',
  'building.robotarm': 'Robotarm',
  'building.robotarm.desc': 'Werkt onvermoeibaar door',
  'building.assembly': 'Lopende band',
  'building.assembly.desc': 'Een hele hal vol munten',
  'building.megafab': 'Mega-fabriek',
  'building.megafab.desc': 'Munten met bakken tegelijk',

  'upgrade.oil': 'Smeerolie',
  'upgrade.turbo': 'Turbomotor',
  'upgrade.precision': 'Precisiegereedschap',
  'upgrade.golden': 'Gouden toetsen',
  'upgrade.prod': 'Alle machines ×{x} sneller',
  'upgrade.payout': 'Elke opdracht ×{x} munten',

  'ach.eerste-munt': 'Eerste munt',
  'ach.eerste-machine': 'Eerste machine',
  'ach.duizend': '1.000 munten verdiend',
  'ach.tienduizend': '10.000 munten verdiend',
  'ach.honderdduizend': '100.000 munten verdiend',
  'ach.combo-25': 'Combo van 25',
  'ach.combo-50': 'Combo van 50',
  'ach.eerste-goud': 'Eerste gouden opdracht',
  'ach.goud-10': '10 gouden opdrachten',
  'ach.vijf-letters': '5 letters geleerd',
  'ach.tien-letters': '10 letters geleerd',
  'ach.alle-letters': 'Alle letters geleerd!',
  'ach.eerste-rebirth': 'Eerste ster',
  'ach.drie-rebirths': 'Drie sterren',
  'ach.honderd-oefeningen': '100 opdrachten gedaan',

  'desktop.title': 'Pak een toetsenbord erbij!',
  'desktop.body': 'Typcoon speel je met een echt toetsenbord — op een laptop of computer. Tot zo!',
};

export function gt(key, vars) {
  const raw = STRINGS[key];
  if (raw == null) return key;
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (_, k) => (k in vars ? String(vars[k]) : `{${k}}`));
}
